### ISSUE TITLE
申请友链

### ISSUE THREAD

**Issue by hslzz** [TIANLI0/TIANLI0#15]
### 申请友链

> pull requsets不知道怎么弄，玩不懂github，所以写这里了

``` yaml
- name: 花生莲子粥
  link: https://blog.hslzz.cn/
  avatar: https://hslzz.cn/assets/img/favicon.png
  descr: 与世无争，不染于泥
```
@TIANLI0
